# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

#source "https://github.com/CocoaPods/Specs.git"
source "https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git"

target 'Swift.IOS.Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift.IOS.Example
  
  # UI (MyLayout swift-version)
  pod 'TangramKit', '~> 1.4.2'
   
  # 
  pod 'ReactiveSwfit'
  
  # web image
  pod 'AlamofireImage', '~> 4.1.0'

end
